--- #YAML:1.0
name: Devel-LeakTrace
version: 0.05
license: perl
distribution_type: module
requires:
  Module::Build: 0.19
  Test::More: 0
recommends: {}
build_requires: {}
conflicts: {}
dynamic_config: 1
provides:
  Devel::LeakTrace:
    file: lib/Devel/LeakTrace.pm
    version: 0.05
generated_by: Module::Build version 0.20
